# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 21:18
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_content', models.TextField(null=True)),
                ('guess_content', models.CharField(max_length=30, null=True)),
                ('start_flag', models.CharField(max_length=1, null=True)),
                ('connect_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20)),
                ('current_content', models.TextField(null=True)),
                ('start', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='First name can only contain characters.', regex='^[A-Za-z]+$')])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Last name can only contain characters.', regex='^[A-Za-z]+$')])),
                ('points', models.IntegerField(blank=True, default=0)),
                ('profile_image', models.ImageField(blank=True, default='user_profile_images/default.jpg', upload_to='user_profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.SlugField(max_length=15, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('e', 'Easy'), ('m', 'Medium'), ('h', 'Hard')], default='e', max_length=1)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='draw_something.Game')),
                ('players', models.ManyToManyField(related_name='players', to='draw_something.Player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='drawer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawer', to='draw_something.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='guesser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guesser', to='draw_something.Player'),
        ),
        migrations.AddField(
            model_name='drawermessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='draw_something.Room'),
        ),
    ]
