# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw_something', '0002_room_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/draw_something/images/default.jpg', upload_to='user_profile_images'),
        ),
    ]
